# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c650549d1df5084e762d5251d4a3d54b"
name = "lunaroz"
handle = "lunaroz"
application_url = "https://served-departure-circle-genre.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://checkout-cruise-medicare-deployment.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://checkout-cruise-medicare-deployment.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,write_customer_data_erasure,write_orders,write_returns"

[auth]
redirect_urls = ["https://served-departure-circle-genre.trycloudflare.com/auth/callback", "https://served-departure-circle-genre.trycloudflare.com/auth/shopify/callback", "https://served-departure-circle-genre.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://served-departure-circle-genre.trycloudflare.com"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
